Diagnostics:
  ClangTidy:
    Add: 
      [
        # "*"
      ]
    Remove:
      [
        # abseil*,
        # fuchsia*,
        # llvmlib*,
        # zircon*,
        # altera*,
        # google-readability-todo,
        # readability-braces-around-statements,
        # hicpp-braces-around-statements,
        # modernize-use-trailing-return-type,
      ]
Index:
  Background: Build